production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  endpoint: <%= ENV['S3_ENDPOINT'] %>
  secure:
  private:
  expires:
  proxy:

development:
  access_key_id:
  secret_access_key:
  bucket:
  endpoint:
  secure:
  private:
  expires:
  proxy:
